In [2]:
import pandas as pd
import random
import tweepy
import random
import time
import GetOldTweets3 as got

In [3]:
consumer_key = "xMqbF6gGhWHWPUg9xw5ziJZpK"
consumer_secret = "RPGgCCRFD2VpyfcPpEVjPbCYPlFIi2cTEImz6BNWzkIXGekibx"
access_key = "1119208863574708224-FwHs7oMskXgPAocqA81D5HrOdwV6tA"
access_token = "1119208863574708224-FwHs7oMskXgPAocqA81D5HrOdwV6tA"
access_secret = "hmlim46RNtaHkFBIHWYYKACAKsUtvsu59YViEjW0bnZ2J"
access_token_secret = "hmlim46RNtaHkFBIHWYYKACAKsUtvsu59YViEjW0bnZ2J"

In [9]:
ironhack = pd.read_csv('/home/jose/Documents/Ironhack/Projects/Final Project/final-project/your-project/notebooks/main/Ironhack/ironhack_twitter_community.csv')
ironhack.describe()

,Unnamed: 0,id,followers_count,friends_count,listed_count,favourites_count,statuses_count
count,12205.000000,1.220500e+04,1.220500e+04,12205.000000,12205.000000,12205.000000,1.220500e+04
mean,6102.000000,1.435787e+17,1.916582e+03,1646.180090,62.505039,2891.769111,4.941899e+03
std,3523.424352,3.247707e+17,2.842752e+04,8315.578048,256.063195,11774.755447,2.221246e+04
min,0.000000,1.353200e+04,0.000000e+00,1.000000,0.000000,0.000000,0.000000e+00
25%,3051.000000,1.407636e+08,7.300000e+01,245.000000,1.000000,52.000000,1.340000e+02
50%,6102.000000,5.245893e+08,2.440000e+02,625.000000,9.000000,382.000000,7.930000e+02
75%,9153.000000,3.063833e+09,7.060000e+02,1450.000000,40.000000,1842.000000,3.307000e+03
max,12204.000000,1.232369e+18,2.878503e+06,401962.000000,9764.000000,597215.000000,1.049781e+06

In [10]:
ironhack_true = ironhack[ironhack['protected']==False]

In [15]:
ironhack_q3 = ironhack_true[(ironhack['statuses_count'] >=793)&
                            (ironhack['statuses_count']<=3307)]

ironhack_q3.head()

/home/jose/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,Unnamed: 0,id,screen_name,location,protected,verified,followers_count,friends_count,listed_count,favourites_count,statuses_count,created_at,default_profile,default_profile_image
8,8,623370781,estebanquirogas,México,False,False,615,269,0,5926,822,Sun Jul 01 03:23:53 +0000 2012,False,False
10,10,228463269,dzubilla,México Distrito Federal,False,False,297,683,4,1191,2174,Sun Dec 19 20:04:11 +0000 2010,True,False
12,12,236532231,Lowenmensch22,"Austin, TX",False,False,206,2103,0,8591,1872,Mon Jan 10 20:16:50 +0000 2011,True,False
25,25,185898028,EngAbdulaziz95,Jeddah,False,False,124,346,2,517,1453,Thu Sep 02 02:42:46 +0000 2010,False,False
27,27,1134815199440134147,MagaliMilbergue,"Ile-de-France, France",False,False,308,284,4,22522,3288,Sat Jun 01 13:33:22 +0000 2019,False,False

In [16]:

def top_function(username): # date format = "2019-08-28"
    username = username
    count = 20# Creation of query object
    tweetCriteria = got.manager.TweetCriteria().setUsername(username)\
                                        .setMaxTweets(count)
    # Creation of list that contains all tweets
    tweets = got.manager.TweetManager.getTweets(tweetCriteria)# Creating list of chosen tweet data
    user_tweets = [[tweet.text, tweet.hashtags] for tweet in tweets]
    
    return user_tweets

In [26]:
#ironhack_q3['applying_function'] = ironhack_q3['screen_name'].apply(top_function)

list_user_tweets = []
count = 0
for x in ironhack_q3['screen_name']  :
    count += 1
    print('Scrapping username number:', count)
    user_tweets = top_function(x)
    list_user_tweets.append(user_tweets)

Scrapping username number: 1
Scrapping username number: 2
Scrapping username number: 3
Scrapping username number: 4
Scrapping username number: 5
Scrapping username number: 6

KeyboardInterrupt:

In [7]:
def top_function(users, start, end): # date format = "2019-08-28"
    count = 0
    tweets_for_dataframe = []
    print('Retrieving data from', len(users),'users.','\n','Starting now.')
    
    
    for username in users: 
        
        time.sleep(random.randrange(0, 1))
        
        tweetCriteria = got.manager.TweetCriteria().setUsername(username)\
                                               .setSince(start)\
                                               .setUntil(end)\
                                               .setMaxTweets(100)\
                                               .setEmoji("unicode")
        tweets = got.manager.TweetManager.getTweets(tweetCriteria)
        
        count+=1
        print('Currently at number', count, '\n', 'Percentage completed: ', (count/len(users)))
    
        for tweet in tweets: 
            tweets_for_dataframe.append([username, tweet.id, tweet.to, tweet.date, tweet.text, tweet.retweets, tweet.favorites, tweet.mentions, tweet.hashtags, tweet.geo])
        
        ds = pd.DataFrame(tweets_for_dataframe, columns = ['user','tweet_id','directed_at','tweet_date', 'text', 'rwtweets','favorites','mentions','hashtags','geo'])
        
    return ds

In [8]:
for k in range(15550,15555): 
    username = meo_followers['screen_name']
    start = '2020-02-01'
    end = '2020-03-01'
    tweets_for_dataframe = []
    ds = pd.DataFrame(columns = ['user','tweet_id','directed_at','tweet_date', 'text', 'retweets','favorites','mentions','hashtags','geo'])

    tweetCriteria = got.manager.TweetCriteria().setUsername(username[k])\
                                               .setSince(start)\
                                               .setUntil(end)\
                                               .setMaxTweets(100)\
                                               .setEmoji("unicode")
    
    tweets = got.manager.TweetManager.getTweets(tweetCriteria)
    
    for tweet in tweets: 
        tweets_for_dataframe.append([username, tweet.id, tweet.to, tweet.date, tweet.text, tweet.retweets, tweet.favorites, tweet.mentions, tweet.hashtags, tweet.geo])
    
    data = pd.DataFrame(tweets_for_dataframe, columns = ['user','tweet_id','directed_at','tweet_date', 'text', 'retweets','favorites','mentions','hashtags','geo'])

In [9]:

def real_top_function(users, start, end): # date format = "2019-08-28"
    count = 0
    tweets_for_dataframe = []
    print('Retrieving data from', len(users),'users.','\n','Starting now.')
    
    
    for username in users['screen_name']: 
        time.sleep(random.randrange(0, 1))
        tweetCriteria = got.manager.TweetCriteria().setUsername(username)\
                                               .setSince(start)\
                                               .setUntil(end)\
                                               .setMaxTweets(1000)\
                                               .setEmoji("unicode")
        tweets = got.manager.TweetManager.getTweets(tweetCriteria)
        
        count+=1
        print('Currently at number', count, '\n', 'Percentage completed: ', (count/len(users)))
    
        for tweet in tweets: 
            tweets_for_dataframe.append([username, tweet.id, tweet.to, tweet.date, tweet.text, tweet.retweets, 
                                         tweet.favorites, tweet.mentions, tweet.hashtags, tweet.geo])
        
        ds = pd.DataFrame(tweets_for_dataframe, columns = ['user','tweet_id','directed_at','tweet_date', 'text', 
                                                           'rwtweets','favorites','mentions','hashtags','geo'])
        
    return ds

In [10]:
data.head()

Empty DataFrame
Columns: [user, tweet_id, directed_at, tweet_date, text, retweets, favorites, mentions, hashtags, geo]
Index: []

In [11]:
data

Empty DataFrame
Columns: [user, tweet_id, directed_at, tweet_date, text, retweets, favorites, mentions, hashtags, geo]
Index: []

In [12]:
meo_followers[400:600]

,id,screen_name,location,followers_count,verified,statuses_count
400,1195704796839366656,SMR_zx6,NaN,86,False,143
401,1230881858801397761,ridasyariff,NaN,0,False,1
402,1230879221930741760,Evanceayo6,NaN,1,False,0
403,1230873647348355073,SBilal74846660,"Fez, Fès-Boulemane",2,False,1
404,1174959790490976256,RafaelV85328975,NaN,89,False,284
...,...,...,...,...,...,...
595,160287231,Kid4Poke,Comi cu de quem ta lendo,2502,False,96458
596,1222008865765707776,Guilher26535539,Planeta Terra,118,False,28
597,1120034751614783488,mertcansahinbu,NaN,546,False,70
598,1226730515090362373,BahjaOmar4,NaN,1,False,14
599,1227316385895927818,Brookly04126883,NaN,7,False,38

In [13]:
complete_dataframe = pd.DataFrame(columns = ['user','tweet_id','directed_at','tweet_date', 'text', 
                                            'rwtweets','favorites','mentions','hashtags','geo'])

complete_dataframe

Empty DataFrame
Columns: [user, tweet_id, directed_at, tweet_date, text, rwtweets, favorites, mentions, hashtags, geo]
Index: []

In [14]:
meo_followers.shape[0]

29552

In [15]:

import getpass
import os
password  = '11519205'

for k in range(0,4):
    print('Starting Round', k)
    complete_dataframe.append(real_top_function(meo_followers[(0+2*k):(2+2*k)], '2020-02-01', '2020-03-01'))

    !echo '11519205' | sudo -S ifconfig eth0 down
    
    !echo '11519205' | sudo -S ifconfig et0 192.168.(random.randrange(0,255).random.randrange(0,255))
   
    !echo '11519205' | sudo -S ifconfig eth0 up

    print('ip changed')
    time.sleep((5))
    
    
    complete_dataframe.to_csv(str('copy'+str(k)+'.csv'))

Starting Round 0
Retrieving data from 2 users.
 Starting now.
Currently at number 1
 Percentage completed:  0.5
Currently at number 2
 Percentage completed:  1.0
[sudo] password for jose: sudo: ifconfig: command not found
/bin/sh: 1: Syntax error: "(" unexpected
[sudo] password for jose: sudo: ifconfig: command not found
ip changed
Starting Round 1
Retrieving data from 2 users.
 Starting now.
Currently at number 1
 Percentage completed:  0.5
Currently at number 2
 Percentage completed:  1.0
[sudo] password for jose: sudo: ifconfig: command not found
/bin/sh: 1: Syntax error: "(" unexpected
[sudo] password for jose: sudo: ifconfig: command not found
ip changed
Starting Round 2
Retrieving data from 2 users.
 Starting now.
Currently at number 1
 Percentage completed:  0.5
Currently at number 2
 Percentage completed:  1.0
[sudo] password for jose: sudo: ifconfig: command not found
/bin/sh: 1: Syntax error: "(" unexpected
[sudo] password for jose: sudo: ifconfig: command not found
ip changed
Starting Round 3
Retrieving data from 2 users.
 Starting now.
Currently at number 1
 Percentage completed:  0.5
Currently at number 2
 Percentage completed:  1.0
[sudo] password for jose: sudo: ifconfig: command not found
/bin/sh: 1: Syntax error: "(" unexpected
[sudo] password for jose: sudo: ifconfig: command not found
ip changed

In [ ]:
complete_dataframe.head()